# sonar-project.properties
sonar.projectKey=shopflow
sonar.projectName=ShopFlow API
sonar.projectVersion=0.1.0
sonar.sources=app
sonar.tests=tests
sonar.language=python
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.pylint.reportPaths=pylint-report.txt
sonar.python.xunit.reportPath=junit-report.xml
sonar.exclusions=**/migrations/**,**/__init__.py,**/venv/**
sonar.test.inclusions=tests/**/*.py
sonar.qualitygate.wait=true

# Seuils de qualité
sonar.coverage.exclusions=**/test_*.py,**/conftest.py
